[build-system]
build-backend = "mesonpy"
requires = [
  "charset-normalizer",
  "meson-python",
  "meson==1.11.2",
  "numpy>=2",
]

[project]
name = "pyc2ray"
version = "0.1.0"
description = "Python-wrapped and Accelerated version of C2Ray"
maintainers = [
  {name = "Michele Bianco", email = "mbianc@ethz.ch"},
  {name = "Tommaso Boschi", email = "tboschi@phys.ethz.ch"}
]

requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "astropy==7.2.1",
  "h5py",
  "mpi4py==4.0.3",
  "numpy>=2",
  "scipy",
  "tools21cm",
]

[project.optional-dependencies]
lint = [
  "pre-commit",
  "ruff==0.16.1",
  "clang-format==22.1.5",
  "mypy==2.3.0",
  "meson==1.11.2",
  "types-PyYAML",
]
test = [
  "pytest",
  "pytest-benchmark",
]
dev = ["pyc2ray[lint,test]"]

[tool.pytest]
testpaths = ["tests"]
addopts = ["--benchmark-skip"]

[tool.meson-python.args]
setup = ["-Dbuildtype=release"]

[tool.mypy]
ignore_missing_imports = true

[tool.ruff.lint]
ignore = ["UP031", "PYI019"]
extend-select = ["F403"]
