def density_to_device(*args, **kwargs): ...
def device_close(*args, **kwargs): ...
def device_init(*args, **kwargs): ...
def do_all_sources(*args, **kwargs): ...
def is_device_init(*args, **kwargs): ...
def photo_table_to_device(*args, **kwargs): ...
def source_data_to_device(*args, **kwargs): ...
